# Generated by Django 2.0.6 on 2018-06-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('path_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
