# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('path_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='products')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
